DROP TABLE Health_Center CASCADE
DROP TABLE Health_Center_Located_at CASCADE
DROP TABLE Police_station CASCADE
DROP TABLE Police_Station_Located_at CASCADE
DROP TABLE Assigned_to CASCADE
DROP TABLE Happened_at CASCADE
DROP TABLE Accident_Event CASCADE
DROP TABLE Location CASCADE